name: 'list-google-enabled-services'
on:
  workflow_dispatch:
jobs:
  run:
    name: 'list-google-enabled-services'
    permissions:
      id-token: write
      contents: read
    runs-on: 'ubuntu-latest'
    steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2.1.3
      with:
        token_format: 'access_token'
        workload_identity_provider: ${{ secrets.PROVIDER_NAME }} # this is the output provider_name from the TF module
        service_account: ${{ secrets.SA_EMAIL }} # this is a SA email configured using the TF module with access to YOUR-GCS-BUCKET
    - name: Set up gcloud Cloud SDK environment
      uses: google-github-actions/setup-gcloud@v2.1.0
    - name: Set credential_file
      run: gcloud auth login --cred-file=${{steps.auth.outputs.credentials_file_path}}
    - name: Run gcloud
      run: gcloud services list
